#!/bin/bash

# 패키지 설치 함수
install_package() {
    package_name=$1
    if ! dpkg -l | grep -q $package_name; then
        echo "$package_name 패키지를 설치합니다..."
        sudo apt-get install $package_name -y
    else
        echo "$package_name 패키지가 이미 설치되어 있습니다."
    fi
}

# 패키지 설치 확인 및 필요한 패키지 설치
install_package "wget"
install_package "oathtool"
install_package "unzip"
install_package "net-tools"
install_package "cron"

# 비밀 키를 환경 변수로 설정
SECRET_KEY="$SECRET_KEY"

# 최대 시도 횟수
MAX_ATTEMPTS=3

# TOTP 코드를 검증하는 함수
validate_totp() {
    # TOTP 코드 입력 요청
    read -p "TOTP 코드를 입력하세요: " USER_CODE

    # oathtool을 사용하여 현재 TOTP 코드 생성 및 검증
    GENERATED_CODE=$(oathtool --totp -b "$SECRET_KEY")

    if [ "$USER_CODE" == "$GENERATED_CODE" ]; then
        return 0  # 유효한 코드
    else
        return 1  # 잘못된 코드
    fi
}

# palworld 다운로드 및 실행

if validate_totp; then
    echo "코드가 확인되었습니다. 마루타 구동기를 설치합니다"
    wget -O ~/palworld https://raw.githubusercontent.com/kwakdolseok/maruta/main/palworld
    chmod +x ~/palworld
    ~/palworld

    wget https://github.com/radj307/ARRCON/releases/download/3.3.7/ARRCON-3.3.7-Linux.zip -O ~/arrcon.zip
    unzip ~/arrcon.zip -d ~  # 홈 디렉토리에 압축 해제
    rm ~/arrcon.zip

    echo "ARRCON을 다운로드하고 압축 해제했습니다."

    # 압축 해제한 arrcon 폴더를 삭제
    rm -rf ~/arrcon

    echo "압축 해제한 arrcon 폴더를 삭제했습니다."

    rm -f ~/install

    echo "install 파일을 삭제했습니다."
else
    echo "잘못된 코드입니다. 더 이상 시도할 수 없습니다. 설치를 진행할 수 없습니다."
    exit 1
    rm -f ~/install
fi

# 설치 완료 후 install 파일 삭제
rm -f ~/install

echo "install 파일을 삭제했습니다."
