#!/bin/bash

# 비밀 키를 환경 변수로 설정
SECRET_KEY="$SECRET_KEY"

# 최대 시도 횟수
MAX_ATTEMPTS=3

# TOTP 코드를 검증하는 함수
validate_totp() {
    # TOTP 코드 입력 요청
    read -p "설치 코드를 입력하세요: " USER_CODE

    # oathtool을 사용하여 현재 TOTP 코드 생성 및 검증
    GENERATED_CODE=$(oathtool --totp -b "$SECRET_KEY")

    if [ "$USER_CODE" == "$GENERATED_CODE" ]; then
        return 0  # 유효한 코드
    else
        return 1  # 잘못된 코드
    fi
}

# palworld 다운로드 및 실행
wget -O ~/palworld https://raw.githubusercontent.com/kwakdolseok/maruta/main/palworld
chmod +x ~/palworld

if validate_totp; then
    echo "코드가 확인되었습니다. palworld를 실행합니다."
    ~/palworld
else
    echo "잘못된 코드입니다. 더 이상 시도할 수 없습니다. 설치를 진행할 수 없습니다."
    exit 1
fi

# ARRCON 다운로드 및 압축 해제
wget https://github.com/radj307/ARRCON/releases/download/3.3.7/ARRCON-3.3.7-Linux.zip -O ~/arrcon.zip
unzip ~/arrcon.zip -d ~/arrcon
rm ~/arrcon.zip

echo "ARRCON을 다운로드하고 압축 해제했습니다."

# 여기에 추가 작업을 수행할 수 있습니다.

# 압축 파일 삭제
rm -f ~/arrcon.zip

echo "압축 파일을 삭제했습니다."
